#!/bin/sh

images="Config.IMAGE_ROOT


pageThumbnailBut0.png
pageThumbnailBut0Down.png
pageThumbnailBut1.png
pageThumbnailBut1Down.png
pageThumbnailBut2.png
pageThumbnailBut2Down.png
pageThumbnailBut3.png
pageThumbnailBut3Down.png
propLine.png
propLineDown.png
propLineOver.png
propDrunk.png
propDrunkDown.png
propDrunkOver.png
propDroneJump.png
propDroneJumpDown.png
propDroneJumpOver.png
propRepeater.png
propRepeaterDown.png
propRepeaterOver.png
propLoopseg.png
propLoopsegDown.png
propLoopsegOver.png
all.png
animals.png
concret.png
keyboard.png
people.png
percussions.png
strings.png
winds.png
allsel.png
animalssel.png
concretsel.png
keyboardsel.png
peoplesel.png
percussionssel.png
stringssel.png
windssel.png
