default: 
#       For this project we don't really want things installed properly... just want the lltimer.so in the tamtam directory
#	python setup.py build install --home=$(TAMTAM_ROOT) 
	python setup.py build
	cp build/lib*/* $(TAMTAM_ROOT)	
clean:
	rm -rf build





